      - name: Generate manifest.json (10.10.x + 10.11.x)
        id: manifest
        shell: bash
        run: |
          #
          # Fester Block: alte funktionierende Version für Jellyfin 10.10.x
          #
          OLD_VERSION="0.3.4.0"
          OLD_TAG="v0.3.4"
          OLD_ABI="10.10.0.0"    # das ist die ABI, die du heute schon im funktionierenden manifest hast
          OLD_URL="https://github.com/Solas79/folder-collection/releases/download/${OLD_TAG}/Jellyfin.Plugin.CollectionsByFolder.zip"
          OLD_CHECKSUM="60f5a54117f8feb5f1f2b777bd128074"   # MD5 von der alten ZIP
          OLD_TIMESTAMP="2025-10-07T08:52:20Z"
          OLD_CHANGELOG="Automatischer Build für ${OLD_TAG} (Jellyfin 10.10.x)"

          #
          # Dynamischer Block: neue Version für Jellyfin 10.11.x
          #
          NEW_TAG="${GITHUB_REF_NAME}"          # z. B. v0.4.0 (kommt vom Release-Tag)
          NEW_VERSION="${NEW_TAG#v}.0"          # v0.4.0 -> 0.4.0.0
          NEW_ABI="10.11.0.0"                   # HIER ggf. anpassen, falls dein 10.11-Server eine andere ABI meldet
          NEW_URL="https://github.com/${{ github.repository }}/releases/download/${NEW_TAG}/Jellyfin.Plugin.CollectionsByFolder.zip"
          NEW_CHECKSUM="${{ steps.md5.outputs.md5 }}"  # MD5 der neu gebauten ZIP
          NEW_TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          NEW_CHANGELOG="Automatischer Build für ${NEW_TAG} (Jellyfin 10.11.x)"

          cat > manifest.json <<JSON
          [
            {
              "category": "Library",
              "guid": "f58f3a40-6a8a-48e8-9b3a-9d7f0b6a3a41",
              "name": "CollectionsByFolder",
              "owner": "Solas79",
              "overview": "Erstellt/aktualisiert Collections anhand des letzten Ordnernamens.",
              "description": "Mehrere Pfade, Präfix/Suffix, Blacklist, Mindestanzahl und manueller Scan.",
              "versions": [
                {
                  "version": "${OLD_VERSION}",
                  "targetAbi": "${OLD_ABI}",
                  "sourceUrl": "${OLD_URL}",
                  "checksum": "${OLD_CHECKSUM}",
                  "timestamp": "${OLD_TIMESTAMP}",
                  "changelog": "${OLD_CHANGELOG}"
                },
                {
                  "version": "${NEW_VERSION}",
                  "targetAbi": "${NEW_ABI}",
                  "sourceUrl": "${NEW_URL}",
                  "checksum": "${NEW_CHECKSUM}",
                  "timestamp": "${NEW_TIMESTAMP}",
                  "changelog": "${NEW_CHANGELOG}"
                }
              ]
            }
          ]
          JSON

          cat manifest.json
