name: Build Jellyfin FolderCollections Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup .NET 8 (with NuGet cache)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: |
            nuget.config
            src/FolderCollectionsPlugin.csproj
            **/packages.lock.json

      - name: Restore (with retry/backoff)
        shell: bash
        run: |
          set -e
          for i in 0 1 2 3 4 5; do
            if dotnet restore src/FolderCollectionsPlugin.csproj --nologo; then
              exit 0
            fi
            echo "Restore failed (attempt $((i+1))). Retrying..."
            sleep $((2**i))
          done
          echo "Restore failed after retries."
          exit 1

      - name: Build (Release)
        run: dotnet build src/FolderCollectionsPlugin.csproj -c Release --no-restore --nologo

      - name: Publish AnyCPU (no build)
        run: dotnet publish src/FolderCollectionsPlugin.csproj -c Release -o publish --no-restore --no-build --nologo

      - name: Archive plugin
        run: |
          cd publish
          zip -r ../FolderCollections.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FolderCollections
          path: FolderCollections.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: FolderCollections

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: FolderCollections.zip
