name: Build Jellyfin FolderCollections Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Add Jellyfin feed
        run: dotnet nuget add source https://repo.jellyfin.org/releases/plugin/v1/index.json --name jellyfin

      - name: Restore dependencies
        run: dotnet restore src/FolderCollectionsPlugin.csproj

      - name: Build (Release)
        run: dotnet build src/FolderCollectionsPlugin.csproj -c Release --no-restore

      - name: Publish AnyCPU
        run: dotnet publish src/FolderCollectionsPlugin.csproj -c Release -o publish --no-restore

      - name: Archive plugin
        run: |
          cd publish
          zip -r ../FolderCollections.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FolderCollections
          path: FolderCollections.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: FolderCollections

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: FolderCollections.zip
